services:
  express:
    build: .
    command: npx nodemon --watch . ./bin/www
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - DEBUG=sample-express:*
      - NODE_ENV=development

